/*The Pythagorean theorem states that the sum of the squares of the sides of 
a right triangle is equal to the square of the hypotenuse.  For example, if two 
sides of a right triangle have lengths of 3 and 4, then the hypotenuse must 
have a length of 5. Together the integers 3, 4, and 5 form a Pythagorean triple. 
There are an infinite number of such triples. Given two positive integers, m 
and n, where m > n, a Pythagorean triple can be generated by the following 
formulas:

side1  =   m^2  –   n^2
side2  =   2 * m * n
hypotenuse  =  m^2  +  n^2

The triple (side1  = 3, side2  = 4, and hypotenuse = 5) is generated by this for­
mula when m = 2 and n =  1. Write a program that takes values for m and n as 
input and displays the values of the Pythagorean triple generated by the for­
mulas above.*/

#include <stdio.h>

int m, n;

int main(void) {
    scanf("%d %d", &m, &n);
    
    if(m < n) {
        int placeHolder = m;
        m = n;
        n = placeHolder;
    }
    
    printf("side 1: %d, side 2: %d, hypotenuse: %d\n", m * m - n * n, 2 * m * n, m * m + n * n);

    return 0;
}
